[package]
name = "thread-pause"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.2"
lazy_static = "1.4.0"
nix = "0.26.1"
spin = "0.9.4"
